using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using RevitGen.Generator;
using Xunit;

namespace RevitGen.Tests
{
    /// <summary>
    /// Unit tests for <see cref="SourceGenerationHelper"/> by examining the output
    /// produced from in-memory compilations.
    /// </summary>
    public class SourceGenerationHelperTests
    {
        private const string AttributeSource = @"
using System;
namespace RevitGen.Attributes
{
    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class RevitCommandAttribute : Attribute
    {
        public string Text { get; }
        public string TabName { get; set; } = ""RevitGen"";
        public string PanelName { get; set; } = ""Commands"";
        public string Icon { get; set; } = """";
        public string ToolTip { get; set; } = """";
        public bool UsingTransaction { get; set; } = true;
        public RevitCommandAttribute(string text) { Text = text; }
    }

    [AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
    public sealed class CommandHandlerAttribute : Attribute { }
}";

        private static INamedTypeSymbol GetClassSymbol(string classSource)
        {
            var parseOptions = CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.CSharp9);
            var compilation = CSharpCompilation.Create(
                "TestAssembly",
                syntaxTrees: new[]
                {
                    CSharpSyntaxTree.ParseText(AttributeSource, parseOptions),
                    CSharpSyntaxTree.ParseText(classSource, parseOptions)
                },
                references: new[]
                {
                    MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                    MetadataReference.CreateFromFile(Assembly.Load("System.Runtime").Location)
                },
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

            return compilation.GlobalNamespace
                .GetNamespaceMembers()
                .SelectMany(GetAllTypes)
                .First(t => t.GetAttributes().Any(a =>
                    a.AttributeClass?.ToDisplayString() == "RevitGen.Attributes.RevitCommandAttribute"));
        }

        private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol ns)
        {
            foreach (var type in ns.GetTypeMembers())
                yield return type;
            foreach (var nested in ns.GetNamespaceMembers())
                foreach (var type in GetAllTypes(nested))
                    yield return type;
        }

        // ── GenerateCommandPartialClass ───────────────────────────────────────

        [Fact]
        public void GenerateCommandPartialClass_ContainsAutoGeneratedComment()
        {
            var classSymbol = GetClassSymbol(@"
using RevitGen.Attributes;
namespace MyAddin
{
    [RevitCommand(""Test"")]
    public partial class MyCmd
    {
        [CommandHandler]
        private void Run() { }
    }
}");
            var result = SourceGenerationHelper.GenerateCommandPartialClass(classSymbol);
            Assert.Contains("// <auto-generated/>", result);
        }

        [Fact]
        public void GenerateCommandPartialClass_ContainsCorrectNamespace()
        {
            var classSymbol = GetClassSymbol(@"
using RevitGen.Attributes;
namespace My.Custom.Namespace
{
    [RevitCommand(""Test"")]
    public partial class MyCmd
    {
        [CommandHandler]
        private void Run() { }
    }
}");
            var result = SourceGenerationHelper.GenerateCommandPartialClass(classSymbol);
            Assert.Contains("namespace My.Custom.Namespace", result);
        }

        [Fact]
        public void GenerateCommandPartialClass_ContainsTransactionAttribute()
        {
            var classSymbol = GetClassSymbol(@"
using RevitGen.Attributes;
namespace MyAddin
{
    [RevitCommand(""Test"")]
    public partial class MyCmd
    {
        [CommandHandler]
        private void Run() { }
    }
}");
            var result = SourceGenerationHelper.GenerateCommandPartialClass(classSymbol);
            Assert.Contains("[Transaction(TransactionMode.Manual)]", result);
        }

        [Fact]
        public void GenerateCommandPartialClass_WithUsingTransaction_IncludesTransactionBlock()
        {
            var classSymbol = GetClassSymbol(@"
using RevitGen.Attributes;
namespace MyAddin
{
    [RevitCommand(""Test"", UsingTransaction = true)]
    public partial class TxCmd
    {
        [CommandHandler]
        private void Run() { }
    }
}");
            var result = SourceGenerationHelper.GenerateCommandPartialClass(classSymbol);
            Assert.Contains("new Transaction(", result);
            Assert.Contains("trans.Start()", result);
        }

        [Fact]
        public void GenerateCommandPartialClass_WithoutUsingTransaction_NoTransactionBlock()
        {
            var classSymbol = GetClassSymbol(@"
using RevitGen.Attributes;
namespace MyAddin
{
    [RevitCommand(""Test"", UsingTransaction = false)]
    public partial class NoTxCmd
    {
        [CommandHandler]
        private void Run() { }
    }
}");
            var result = SourceGenerationHelper.GenerateCommandPartialClass(classSymbol);
            Assert.DoesNotContain("new Transaction(", result);
        }

        [Fact]
        public void GenerateCommandPartialClass_CallsHandlerMethod()
        {
            var classSymbol = GetClassSymbol(@"
using RevitGen.Attributes;
namespace MyAddin
{
    [RevitCommand(""Test"")]
    public partial class MyCmd
    {
        [CommandHandler]
        private void Execute() { }
    }
}");
            var result = SourceGenerationHelper.GenerateCommandPartialClass(classSymbol);
            Assert.Contains("this.Execute()", result);
        }

        [Fact]
        public void GenerateCommandPartialClass_WithNoHandlerMethod_ReturnsErrorComment()
        {
            var classSymbol = GetClassSymbol(@"
using RevitGen.Attributes;
namespace MyAddin
{
    [RevitCommand(""Test"")]
    public partial class BadCmd
    {
        private void Run() { }
    }
}");
            var result = SourceGenerationHelper.GenerateCommandPartialClass(classSymbol);
            Assert.StartsWith("// 错误", result);
        }

        // ── GenerateApplicationClass ──────────────────────────────────────────

        [Fact]
        public void GenerateApplicationClass_ContainsAutoGeneratedComment()
        {
            var classSymbol = GetClassSymbol(@"
using RevitGen.Attributes;
namespace MyAddin
{
    [RevitCommand(""Test"")]
    public partial class MyCmd
    {
        [CommandHandler]
        private void Run() { }
    }
}");
            var result = SourceGenerationHelper.GenerateApplicationClass(
                new[] { classSymbol });
            Assert.Contains("// <auto-generated/>", result);
        }

        [Fact]
        public void GenerateApplicationClass_ContainsRevitGenRuntimeNamespace()
        {
            var classSymbol = GetClassSymbol(@"
using RevitGen.Attributes;
namespace MyAddin
{
    [RevitCommand(""Test"")]
    public partial class MyCmd
    {
        [CommandHandler]
        private void Run() { }
    }
}");
            var result = SourceGenerationHelper.GenerateApplicationClass(
                new[] { classSymbol });
            Assert.Contains("namespace RevitGen.Runtime", result);
        }

        [Fact]
        public void GenerateApplicationClass_MultipleCommandsInSamePanel_OneCreateRibbonPanelCall()
        {
            var source = @"
using RevitGen.Attributes;
namespace MyAddin
{
    [RevitCommand(""Cmd1"", TabName = ""MyTab"", PanelName = ""MyPanel"")]
    public partial class CmdA
    {
        [CommandHandler]
        private void Run() { }
    }

    [RevitCommand(""Cmd2"", TabName = ""MyTab"", PanelName = ""MyPanel"")]
    public partial class CmdB
    {
        [CommandHandler]
        private void Run() { }
    }
}";
            var parseOptions = CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.CSharp9);
            var compilation = CSharpCompilation.Create(
                "TestAssembly",
                syntaxTrees: new[]
                {
                    CSharpSyntaxTree.ParseText(AttributeSource, parseOptions),
                    CSharpSyntaxTree.ParseText(source, parseOptions)
                },
                references: new[]
                {
                    MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                    MetadataReference.CreateFromFile(Assembly.Load("System.Runtime").Location)
                },
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

            var symbols = compilation.GlobalNamespace
                .GetNamespaceMembers()
                .SelectMany(GetAllTypes)
                .Where(t => t.GetAttributes().Any(a =>
                    a.AttributeClass?.ToDisplayString() == "RevitGen.Attributes.RevitCommandAttribute"))
                .ToList();

            var result = SourceGenerationHelper.GenerateApplicationClass(symbols);

            // Both commands reference the same panel variable
            int panelCreations = System.Text.RegularExpressions.Regex
                .Matches(result, "CreateRibbonPanel").Count;
            Assert.Equal(1, panelCreations);
        }
    }
}
