using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

using Microsoft.CodeAnalysis;

namespace RevitGen.Generator
{
    /// <summary>
    /// 生成统一 Bootstrap、默认 IExternalApplication 和 Ribbon 注册代码。
    /// </summary>
    internal static class ApplicationGenerationHelper
    {
        private const string CommandAttribute = "RevitGen.Attributes.RevitCommandAttribute";
        private const string CommandHandlerAttribute = "RevitGen.Attributes.CommandHandlerAttribute";
        private const string AvailabilityAttribute = "RevitGen.Attributes.CommandAvailabilityAttribute";

        /// <summary>
        /// 根据所有注册类型生成唯一应用入口。
        /// </summary>
        public static string Generate(IReadOnlyCollection<INamedTypeSymbol> symbols)
        {
            var commands = symbols
                .Where(symbol => SymbolUtilities.HasAttribute(symbol, CommandAttribute))
                .Where(IsValidCommand)
                .Select(CreateCommandData)
                .OrderBy(command => command.TabName, StringComparer.Ordinal)
                .ThenBy(command => command.PanelName, StringComparer.Ordinal)
                .ThenBy(command => command.Order)
                .ThenBy(command => command.RuntimeTypeName, StringComparer.Ordinal)
                .ToList();
            var updaters = GetTypes(symbols, RevitIncrementalGenerator.UpdaterAttribute);
            var eventContainers = GetTypes(symbols, RevitIncrementalGenerator.EventContainerAttribute);
            var dockablePanes = GetTypes(symbols, RevitIncrementalGenerator.DockablePaneAttribute);

            var source = new StringBuilder();
            AppendHeader(source);
            AppendImageHelpers(source);
            AppendStartup(source, commands, updaters, eventContainers, dockablePanes);
            AppendShutdown(source, updaters, eventContainers);
            source.AppendLine("    }");
            source.AppendLine();
            source.AppendLine("    public sealed class RevitGenApplication : global::Autodesk.Revit.UI.IExternalApplication");
            source.AppendLine("    {");
            source.AppendLine("        public global::Autodesk.Revit.UI.Result OnStartup(global::Autodesk.Revit.UI.UIControlledApplication application)");
            source.AppendLine("        {");
            source.AppendLine("            return RevitGenBootstrap.Startup(application);");
            source.AppendLine("        }");
            source.AppendLine();
            source.AppendLine("        public global::Autodesk.Revit.UI.Result OnShutdown(global::Autodesk.Revit.UI.UIControlledApplication application)");
            source.AppendLine("        {");
            source.AppendLine("            return RevitGenBootstrap.Shutdown(application);");
            source.AppendLine("        }");
            source.AppendLine("    }");
            source.AppendLine("}");
            return source.ToString();
        }

        /// <summary>
        /// 写入生成文件头和 Bootstrap 类型声明。
        /// </summary>
        private static void AppendHeader(StringBuilder source)
        {
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("namespace RevitGen.Runtime");
            source.AppendLine("{");
            source.AppendLine("    public static class RevitGenBootstrap");
            source.AppendLine("    {");
            source.AppendLine("        private static global::System.Resources.ResourceManager __resourceManager;");
        }

        /// <summary>
        /// 写入嵌入资源和 ResX 图标加载方法。
        /// </summary>
        private static void AppendImageHelpers(StringBuilder source)
        {
            source.AppendLine("        private static global::System.Windows.Media.Imaging.BitmapSource LoadImage(global::System.Reflection.Assembly assembly, string resource)");
            source.AppendLine("        {");
            source.AppendLine("            if (string.IsNullOrEmpty(resource)) return null;");
            source.AppendLine("            try");
            source.AppendLine("            {");
            source.AppendLine("                if (!string.IsNullOrEmpty(global::System.IO.Path.GetExtension(resource)))");
            source.AppendLine("                {");
            source.AppendLine("                    var resourceName = assembly.GetName().Name + \".\" + resource.Replace('/', '.').Replace('\\\\', '.');");
            source.AppendLine("                    using (var stream = assembly.GetManifestResourceStream(resourceName))");
            source.AppendLine("                    {");
            source.AppendLine("                        if (stream == null) return null;");
            source.AppendLine("                        var image = new global::System.Windows.Media.Imaging.BitmapImage();");
            source.AppendLine("                        image.BeginInit();");
            source.AppendLine("                        image.CacheOption = global::System.Windows.Media.Imaging.BitmapCacheOption.OnLoad;");
            source.AppendLine("                        image.StreamSource = stream;");
            source.AppendLine("                        image.EndInit();");
            source.AppendLine("                        image.Freeze();");
            source.AppendLine("                        return image;");
            source.AppendLine("                    }");
            source.AppendLine("                }");
            source.AppendLine("                if (__resourceManager == null)");
            source.AppendLine("                    __resourceManager = new global::System.Resources.ResourceManager(assembly.GetName().Name + \".Properties.Resources\", assembly);");
            source.AppendLine("                var bitmap = __resourceManager.GetObject(resource);");
            source.AppendLine("                if (bitmap == null) return null;");
            source.AppendLine("                var existingSource = bitmap as global::System.Windows.Media.Imaging.BitmapSource;");
            source.AppendLine("                if (existingSource != null) return existingSource;");
            source.AppendLine("                using (var stream = new global::System.IO.MemoryStream())");
            source.AppendLine("                {");
            source.AppendLine("                    var rawFormat = bitmap.GetType().GetProperty(\"RawFormat\")?.GetValue(bitmap, null);");
            source.AppendLine("                    if (rawFormat == null) return null;");
            source.AppendLine("                    var saveMethod = bitmap.GetType().GetMethod(\"Save\", new[] { typeof(global::System.IO.Stream), rawFormat.GetType() });");
            source.AppendLine("                    if (saveMethod == null) return null;");
            source.AppendLine("                    saveMethod.Invoke(bitmap, new[] { (object)stream, rawFormat });");
            source.AppendLine("                    stream.Position = 0;");
            source.AppendLine("                    var image = new global::System.Windows.Media.Imaging.BitmapImage();");
            source.AppendLine("                    image.BeginInit();");
            source.AppendLine("                    image.CacheOption = global::System.Windows.Media.Imaging.BitmapCacheOption.OnLoad;");
            source.AppendLine("                    image.StreamSource = stream;");
            source.AppendLine("                    image.EndInit();");
            source.AppendLine("                    image.Freeze();");
            source.AppendLine("                    return image;");
            source.AppendLine("                }");
            source.AppendLine("            }");
            source.AppendLine("            catch { return null; }");
            source.AppendLine("        }");
            source.AppendLine();
        }

        /// <summary>
        /// 写入启动注册流程和 Ribbon 创建代码。
        /// </summary>
        private static void AppendStartup(
            StringBuilder source,
            IReadOnlyList<CommandData> commands,
            IReadOnlyList<INamedTypeSymbol> updaters,
            IReadOnlyList<INamedTypeSymbol> eventContainers,
            IReadOnlyList<INamedTypeSymbol> dockablePanes)
        {
            source.AppendLine("        public static global::Autodesk.Revit.UI.Result Startup(global::Autodesk.Revit.UI.UIControlledApplication application)");
            source.AppendLine("        {");
            source.AppendLine("            try");
            source.AppendLine("            {");
            source.AppendLine("                var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();");
            source.AppendLine("                var assemblyPath = assembly.Location;");
            AppendRibbon(source, commands);
            foreach (var pane in dockablePanes)
                source.Append("                ").Append(SymbolUtilities.GetCodeTypeName(pane)).AppendLine(".__RevitGenRegister(application);");
            foreach (var updater in updaters)
                source.Append("                ").Append(SymbolUtilities.GetCodeTypeName(updater)).AppendLine(".__RevitGenRegister(application);");
            foreach (var container in eventContainers)
                source.Append("                ").Append(SymbolUtilities.GetCodeTypeName(container)).AppendLine(".__RevitGenRegister(application);");
            source.AppendLine("                return global::Autodesk.Revit.UI.Result.Succeeded;");
            source.AppendLine("            }");
            source.AppendLine("            catch");
            source.AppendLine("            {");
            source.AppendLine("                return global::Autodesk.Revit.UI.Result.Failed;");
            source.AppendLine("            }");
            source.AppendLine("        }");
            source.AppendLine();
        }

        /// <summary>
        /// 写入关闭阶段的对称清理流程。
        /// </summary>
        private static void AppendShutdown(
            StringBuilder source,
            IReadOnlyList<INamedTypeSymbol> updaters,
            IReadOnlyList<INamedTypeSymbol> eventContainers)
        {
            source.AppendLine("        public static global::Autodesk.Revit.UI.Result Shutdown(global::Autodesk.Revit.UI.UIControlledApplication application)");
            source.AppendLine("        {");
            source.AppendLine("            try");
            source.AppendLine("            {");
            foreach (var container in eventContainers.Reverse())
                source.Append("                ").Append(SymbolUtilities.GetCodeTypeName(container)).AppendLine(".__RevitGenUnregister(application);");
            foreach (var updater in updaters.Reverse())
                source.Append("                ").Append(SymbolUtilities.GetCodeTypeName(updater)).AppendLine(".__RevitGenUnregister();");
            source.AppendLine("                return global::Autodesk.Revit.UI.Result.Succeeded;");
            source.AppendLine("            }");
            source.AppendLine("            catch");
            source.AppendLine("            {");
            source.AppendLine("                return global::Autodesk.Revit.UI.Result.Failed;");
            source.AppendLine("            }");
            source.AppendLine("        }");
        }

        /// <summary>
        /// 按 Tab、Panel 和按钮组写入 Ribbon 创建代码。
        /// </summary>
        private static void AppendRibbon(StringBuilder source, IReadOnlyList<CommandData> commands)
        {
            var panelIndex = 0;
            foreach (var tabGroup in commands.GroupBy(command => command.TabName, StringComparer.Ordinal))
            {
                if (!string.IsNullOrEmpty(tabGroup.Key))
                {
                    source.Append("                try { application.CreateRibbonTab(\"")
                        .Append(Escape(tabGroup.Key)).AppendLine("\"); } catch { }");
                }

                foreach (var panelGroup in tabGroup.GroupBy(command => command.PanelName, StringComparer.Ordinal))
                {
                    var panelVariable = "panel_" + panelIndex++;
                    source.Append("                var ").Append(panelVariable).Append(" = application.CreateRibbonPanel(");
                    if (!string.IsNullOrEmpty(tabGroup.Key))
                        source.Append('"').Append(Escape(tabGroup.Key)).Append("\", ");
                    source.Append('"').Append(Escape(panelGroup.Key)).AppendLine("\");");

                    foreach (var command in panelGroup.Where(item => string.IsNullOrEmpty(item.GroupName)))
                    {
                        if (command.AddSeparatorBefore) source.Append("                ").Append(panelVariable).AppendLine(".AddSeparator();");
                        AppendPushButtonData(source, command, "                ");
                        source.Append("                ").Append(panelVariable).Append(".AddItem(").Append(command.VariableName).AppendLine(");");
                    }

                    foreach (var group in panelGroup.Where(item => !string.IsNullOrEmpty(item.GroupName))
                                 .GroupBy(item => item.GroupName, StringComparer.Ordinal))
                    {
                        AppendButtonGroup(source, panelVariable, group.OrderBy(item => item.Order).ToList());
                    }
                }
            }
        }

        /// <summary>
        /// 写入一个普通 PushButtonData 及其可选属性。
        /// </summary>
        private static void AppendPushButtonData(StringBuilder source, CommandData command, string indent)
        {
            source.Append(indent).Append("var ").Append(command.VariableName).Append(" = new global::Autodesk.Revit.UI.PushButtonData(\"")
                .Append(Escape("cmd_" + command.StableName)).Append("\", \"").Append(Escape(command.Text))
                .Append("\", assemblyPath, \"").Append(Escape(command.RuntimeTypeName)).AppendLine("\");");
            if (!string.IsNullOrEmpty(command.ToolTip))
                source.Append(indent).Append(command.VariableName).Append(".ToolTip = \"").Append(Escape(command.ToolTip)).AppendLine("\";");
            if (!string.IsNullOrEmpty(command.LongDescription))
                source.Append(indent).Append(command.VariableName).Append(".LongDescription = \"").Append(Escape(command.LongDescription)).AppendLine("\";");
            if (!string.IsNullOrEmpty(command.SmallIcon))
                source.Append(indent).Append(command.VariableName).Append(".Image = LoadImage(assembly, \"").Append(Escape(command.SmallIcon)).AppendLine("\");");
            if (!string.IsNullOrEmpty(command.LargeIcon))
                source.Append(indent).Append(command.VariableName).Append(".LargeImage = LoadImage(assembly, \"").Append(Escape(command.LargeIcon)).AppendLine("\");");
            if (!string.IsNullOrEmpty(command.HelpUrl))
                source.Append(indent).Append(command.VariableName).Append(".SetContextualHelp(new global::Autodesk.Revit.UI.ContextualHelp(global::Autodesk.Revit.UI.ContextualHelpType.Url, \"")
                    .Append(Escape(command.HelpUrl)).AppendLine("\"));");
            if (command.HasAvailability)
                source.Append(indent).Append(command.VariableName).Append(".AvailabilityClassName = \"").Append(Escape(command.RuntimeTypeName)).AppendLine("\";");
        }

        /// <summary>
        /// 写入 Pulldown、SplitButton 或 Stacked 按钮组。
        /// </summary>
        private static void AppendButtonGroup(StringBuilder source, string panelVariable, IReadOnlyList<CommandData> commands)
        {
            if (commands.Count == 0) return;
            var groupType = commands[0].GroupType;
            foreach (var command in commands) AppendPushButtonData(source, command, "                ");

            if (groupType == 3 && commands.Count >= 2 && commands.Count <= 3)
            {
                source.Append("                ").Append(panelVariable).Append(".AddStackedItems(")
                    .Append(string.Join(", ", commands.Select(command => command.VariableName))).AppendLine(");");
                return;
            }

            var stableGroupName = Sanitize(commands[0].GroupName + "_" + commands[0].PanelName);
            var dataType = groupType == 2 ? "SplitButtonData" : "PulldownButtonData";
            var resultType = groupType == 2 ? "SplitButton" : "PulldownButton";
            source.Append("                var groupData_").Append(stableGroupName).Append(" = new global::Autodesk.Revit.UI.")
                .Append(dataType).Append("(\"group_").Append(Escape(stableGroupName)).Append("\", \"")
                .Append(Escape(commands[0].GroupName)).AppendLine("\");");
            source.Append("                var group_").Append(stableGroupName).Append(" = ").Append(panelVariable)
                .Append(".AddItem(groupData_").Append(stableGroupName).Append(") as global::Autodesk.Revit.UI.")
                .Append(resultType).AppendLine(";");
            foreach (var command in commands)
                source.Append("                group_").Append(stableGroupName).Append(".AddPushButton(").Append(command.VariableName).AppendLine(");");
        }

        /// <summary>
        /// 从类型集合中筛选带指定特性的类型。
        /// </summary>
        private static IReadOnlyList<INamedTypeSymbol> GetTypes(
            IEnumerable<INamedTypeSymbol> symbols,
            string attributeName)
        {
            return symbols.Where(symbol => SymbolUtilities.HasAttribute(symbol, attributeName))
                .OrderBy(symbol => symbol.ToDisplayString(), StringComparer.Ordinal)
                .ToList();
        }

        /// <summary>
        /// 判断命令是否具有可生成的唯一 Handler。
        /// </summary>
        private static bool IsValidCommand(INamedTypeSymbol symbol)
        {
            var handlers = symbol.GetMembers().OfType<IMethodSymbol>()
                .Where(method => SymbolUtilities.HasAttribute(method, CommandHandlerAttribute))
                .ToList();
            return symbol.DeclaredAccessibility == Accessibility.Public &&
                   handlers.Count == 1 && !handlers[0].IsStatic && handlers[0].ReturnsVoid && handlers[0].Parameters.Length == 0;
        }

        /// <summary>
        /// 将命令 Symbol 转换成 Ribbon 输出模型。
        /// </summary>
        private static CommandData CreateCommandData(INamedTypeSymbol symbol)
        {
            var attribute = SymbolUtilities.GetAttribute(symbol, CommandAttribute);
            var icon = GetNamed(attribute, "Icon", string.Empty);
            var largeIcon = GetNamed(attribute, "LargeIcon", string.Empty);
            return new CommandData
            {
                Text = attribute.ConstructorArguments.Length == 0
                    ? symbol.Name
                    : attribute.ConstructorArguments[0].Value as string ?? symbol.Name,
                TabName = GetNamed(attribute, "TabName", "RevitGen"),
                PanelName = GetNamed(attribute, "PanelName", "Commands"),
                ToolTip = GetNamed(attribute, "ToolTip", string.Empty),
                SmallIcon = GetNamed(attribute, "SmallIcon", string.Empty),
                LargeIcon = string.IsNullOrEmpty(largeIcon) ? icon : largeIcon,
                LongDescription = GetNamed(attribute, "LongDescription", string.Empty),
                HelpUrl = GetNamed(attribute, "HelpUrl", string.Empty),
                Order = GetNamed(attribute, "Order", 0),
                AddSeparatorBefore = GetNamed(attribute, "AddSeparatorBefore", false),
                GroupName = GetNamed(attribute, "GroupName", string.Empty),
                GroupType = GetNamed(attribute, "GroupType", 0),
                RuntimeTypeName = SymbolUtilities.GetRuntimeTypeName(symbol),
                StableName = Sanitize(symbol.ToDisplayString()),
                HasAvailability = symbol.GetMembers().OfType<IMethodSymbol>()
                    .Any(method => SymbolUtilities.HasAttribute(method, AvailabilityAttribute))
            };
        }

        private static T GetNamed<T>(AttributeData attribute, string name, T defaultValue)
        {
            return SymbolUtilities.GetNamedArgument(attribute, name, defaultValue);
        }

        private static string Escape(string value)
        {
            return SymbolUtilities.EscapeString(value);
        }

        private static string Sanitize(string value)
        {
            return Regex.Replace(value ?? string.Empty, @"[^A-Za-z0-9_]", "_");
        }

        private sealed class CommandData
        {
            public string Text { get; set; }
            public string TabName { get; set; }
            public string PanelName { get; set; }
            public string ToolTip { get; set; }
            public string SmallIcon { get; set; }
            public string LargeIcon { get; set; }
            public string LongDescription { get; set; }
            public string HelpUrl { get; set; }
            public string GroupName { get; set; }
            public string RuntimeTypeName { get; set; }
            public string StableName { get; set; }
            public int Order { get; set; }
            public int GroupType { get; set; }
            public bool AddSeparatorBefore { get; set; }
            public bool HasAvailability { get; set; }
            public string VariableName => "pbd_" + StableName;
        }
    }
}
