// <auto-generated is NOT set here — this is hand-written template code>

namespace RevitGen.Generator
{
    /// <summary>
    /// Contains parameterized string templates used by <see cref="SourceGenerationHelper"/>
    /// to produce generated C# source code.  Each template uses {0}, {1}, … placeholders
    /// that are filled in via <see cref="string.Format"/>.  Templates that contain curly
    /// braces as part of the emitted C# code escape them as {{ and }}.
    /// </summary>
    internal static class CodeTemplates
    {
        // ── Command partial class ────────────────────────────────────────────

        /// <summary>
        /// Full template for the generated command partial class.
        /// Placeholders: {0} = namespace, {1} = class name, {2} = execute body
        /// </summary>
        public const string CommandPartialClass =
@"// <auto-generated/>
namespace {0}
{{
    using Autodesk.Revit.DB;
    using Autodesk.Revit.UI;
    using Autodesk.Revit.Attributes;
    using System.ComponentModel;

    [Transaction(TransactionMode.Manual)]
    public partial class {1} : IExternalCommand
    {{
        private ExternalCommandData _commandData;
        public UIApplication UIApplication => _commandData.Application;
        public UIDocument UIDocument => UIApplication.ActiveUIDocument;
        public Document Document => UIDocument.Document;
        public View ActiveView => UIDocument.ActiveView;
        public Result Result {{ get; set; }} = Result.Succeeded;
        public string ErrorMessage {{ get; set; }} = string.Empty;
        public ElementSet ElementSet {{ get; private set; }}

        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
        {{
            this._commandData = commandData;
            this.ElementSet = elements;

            try
            {{
{2}
            }}
            catch (System.Exception ex)
            {{
                this.ErrorMessage = ex.ToString();
                this.Result = Result.Failed;
            }}

            message = this.ErrorMessage;
            return this.Result;
        }}
    }}
}}
";

        /// <summary>
        /// Execute-body template when the command is wrapped in a Revit transaction.
        /// Placeholders: {0} = transaction name (class name), {1} = handler method name
        /// </summary>
        public const string TransactionExecuteBody =
@"                using (var trans = new Transaction(this.Document, ""{0}""))
                {{
                    trans.Start();
                    this.{1}();
                    if (this.Result == Result.Succeeded) trans.Commit(); else trans.RollBack();
                }}";

        /// <summary>
        /// Execute-body template when no transaction is used.
        /// Placeholders: {0} = handler method name
        /// </summary>
        public const string DirectExecuteBody = "                this.{0}();";

        // ── Application class ────────────────────────────────────────────────

        /// <summary>
        /// Static header for the generated <c>RevitGenApplication</c> class, up to the
        /// beginning of the dynamic ribbon-creation code inside <c>OnStartup</c>.
        /// This string is used verbatim (no format placeholders) because the generated
        /// C# code it contains already uses curly braces and string interpolation.
        /// </summary>
        public const string ApplicationClassHeader =
@"// <auto-generated/>
using Autodesk.Revit.UI;
using System;
using System.Reflection;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.IO;
using System.Drawing;
using System.Resources;

namespace RevitGen.Runtime
{
    public class RevitGenApplication : IExternalApplication
    {
        private static ResourceManager _resourceManager;

        private BitmapSource BitmapToImageSource(Bitmap bitmap)
        {
            if (bitmap == null) return null;
            using (MemoryStream stream = new MemoryStream())
            {
                bitmap.Save(stream, System.Drawing.Imaging.ImageFormat.Png);
                stream.Position = 0;
                BitmapImage result = new BitmapImage();
                result.BeginInit();
                result.CacheOption = BitmapCacheOption.OnLoad;
                result.StreamSource = stream;
                result.EndInit();
                result.Freeze();
                return result;
            }
        }

        private BitmapSource LoadImageFromEmbeddedResource(Assembly assembly, string resourcePath)
        {
            try
            {
                string assemblyName = assembly.GetName().Name;
                string resourceName = $""{assemblyName}.{resourcePath.Replace('/', '.').Replace('\\', '.')}"";
                using (Stream stream = assembly.GetManifestResourceStream(resourceName))
                {
                    if (stream == null) return null;
                    var image = new BitmapImage();
                    image.BeginInit();
                    image.StreamSource = stream;
                    image.CacheOption = BitmapCacheOption.OnLoad;
                    image.EndInit();
                    image.Freeze();
                    return image;
                }
            }
            catch { return null; }
        }

        public Result OnStartup(UIControlledApplication app)
        {
            var assembly = Assembly.GetExecutingAssembly();
            string assemblyPath = assembly.Location;

            if (_resourceManager == null)
            {
                string resourceName = assembly.GetName().Name + "".Properties.Resources"";
                try { _resourceManager = new ResourceManager(resourceName, assembly); } catch { /* Ignore if ResX does not exist */ }
            }

";

        /// <summary>
        /// Static footer that closes <c>OnStartup</c>, adds <c>OnShutdown</c>, and closes
        /// the class and namespace.  Used verbatim (no format placeholders).
        /// </summary>
        public const string ApplicationClassFooter =
@"            return Result.Succeeded;
        }
        public Result OnShutdown(UIControlledApplication app) => Result.Succeeded;
    }
}
";

        // ── Per-item ribbon templates (used with string.Format) ──────────────

        /// <summary>
        /// Template for creating a ribbon tab.
        /// Placeholders: {0} = tab name
        /// </summary>
        public const string CreateRibbonTab =
            "            try {{ app.CreateRibbonTab(\"{0}\"); }} catch {{ /* Tab already exists */ }}";

        /// <summary>
        /// Template for creating a ribbon panel on a named tab.
        /// Placeholders: {0} = tab name, {1} = panel name, {2} = panel variable name
        /// </summary>
        public const string CreateRibbonPanelWithTab =
            "            RibbonPanel {2} = app.CreateRibbonPanel(\"{0}\", \"{1}\");";

        /// <summary>
        /// Template for creating a ribbon panel on the default Add-Ins tab.
        /// Placeholders: {0} = panel name, {1} = panel variable name
        /// </summary>
        public const string CreateRibbonPanelDefault =
            "            RibbonPanel {1} = app.CreateRibbonPanel(\"{0}\");";

        /// <summary>
        /// Template for creating <c>PushButtonData</c>.
        /// Placeholders: {0} = command name (used as identifier suffix), {1} = button text,
        ///               {2} = fully-qualified class name
        /// </summary>
        public const string PushButtonData =
            "            var pbd_{0} = new PushButtonData(\"cmd_{0}\", \"{1}\", assemblyPath, \"{2}\");";

        /// <summary>
        /// Template for setting a button tooltip.
        /// Placeholders: {0} = command name, {1} = tooltip text
        /// </summary>
        public const string ButtonToolTip =
            "            pbd_{0}.ToolTip = \"{1}\";";

        /// <summary>
        /// Template for loading a button icon — handles both embedded-file paths (with an
        /// extension) and <c>.resx</c> resource names (without an extension) in a single block.
        /// Placeholders: {0} = command name, {1} = icon path or resource name
        /// </summary>
        public const string ButtonIcon =
@"            {{
                string iconExtension = System.IO.Path.GetExtension(""{1}"");
                if (!string.IsNullOrEmpty(iconExtension))
                {{
                    pbd_{0}.LargeImage = LoadImageFromEmbeddedResource(assembly, ""{1}"");
                }}
                else
                {{
                    if (_resourceManager != null)
                    {{
                        try
                        {{
                            var iconBitmap = (Bitmap)_resourceManager.GetObject(""{1}"");
                            pbd_{0}.LargeImage = BitmapToImageSource(iconBitmap);
                        }}
                        catch {{ /* Resource not found or failed to load */ }}
                    }}
                }}
            }}";

        /// <summary>
        /// Template for adding a push-button to a panel.
        /// Placeholders: {0} = panel variable name, {1} = command name
        /// </summary>
        public const string AddButtonToPanel =
            "            {0}.AddItem(pbd_{1});";
    }
}
