using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;

namespace RevitGen.Generator
{
    /// <summary>
    /// 生成命令之外的 Revit 常用接口实现。
    /// </summary>
    internal static class FeatureGenerationHelper
    {
        private const string ExternalEventHandlerAttribute = "RevitGen.Attributes.ExternalEventHandlerAttribute";
        private const string UpdaterHandlerAttribute = "RevitGen.Attributes.UpdaterHandlerAttribute";
        private const string UpdaterTriggerAttribute = "RevitGen.Attributes.UpdaterTriggerAttribute";
        private const string RevitEventAttribute = "RevitGen.Attributes.RevitEventAttribute";
        private const string SchemaFieldAttribute = "RevitGen.Attributes.RevitSchemaFieldAttribute";
        private const string SharedParameterAttribute = "RevitGen.Attributes.RevitSharedParameterAttribute";

        /// <summary>
        /// 根据模块类型校验并生成源码。
        /// </summary>
        public static bool TryGenerate(
            SourceProductionContext context,
            INamedTypeSymbol symbol,
            FeatureKind kind,
            out string source)
        {
            switch (kind)
            {
                case FeatureKind.ExternalEvent:
                    return TryGenerateExternalEvent(context, symbol, out source);
                case FeatureKind.Updater:
                    return TryGenerateUpdater(context, symbol, out source);
                case FeatureKind.EventContainer:
                    return TryGenerateEventContainer(context, symbol, out source);
                case FeatureKind.DockablePane:
                    return TryGenerateDockablePane(context, symbol, out source);
                case FeatureKind.Schema:
                    return TryGenerateSchema(context, symbol, out source);
                case FeatureKind.SharedParameters:
                    return TryGenerateSharedParameters(context, symbol, out source);
                default:
                    source = string.Empty;
                    return false;
            }
        }

        /// <summary>
        /// 生成 IExternalEventHandler 实现和显式创建入口。
        /// </summary>
        private static bool TryGenerateExternalEvent(
            SourceProductionContext context,
            INamedTypeSymbol symbol,
            out string source)
        {
            source = string.Empty;
            if (!GeneratorValidation.ValidateSingleHandler(
                    context, symbol, ExternalEventHandlerAttribute, "ExternalEventHandler", true)) return false;

            var method = GetMarkedMethods(symbol, ExternalEventHandlerAttribute).Single();
            var attribute = SymbolUtilities.GetAttribute(symbol, RevitIncrementalGenerator.ExternalEventAttribute);
            var eventName = SymbolUtilities.GetNamedArgument(attribute, "Name", string.Empty);
            if (string.IsNullOrWhiteSpace(eventName)) eventName = symbol.Name;

            var builder = new StringBuilder("// <auto-generated/>\n");
            var closeCount = SymbolUtilities.AppendPartialTypeStart(
                builder, symbol, "global::Autodesk.Revit.UI.IExternalEventHandler");
            var indent = new string(' ', closeCount * 4);
            builder.Append(indent).AppendLine("public global::Autodesk.Revit.UI.UIApplication UIApplication { get; private set; }");
            builder.Append(indent).AppendLine("public void Execute(global::Autodesk.Revit.UI.UIApplication application)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    this.UIApplication = application;");
            builder.Append(indent).Append("    this.").Append(method.Name).Append('(');
            if (method.Parameters.Length == 1) builder.Append("application");
            builder.AppendLine(");");
            builder.Append(indent).AppendLine("}");
            builder.Append(indent).Append("public string GetName() => \"")
                .Append(SymbolUtilities.EscapeString(eventName)).AppendLine("\";");
            builder.Append(indent).AppendLine("public global::Autodesk.Revit.UI.ExternalEvent CreateExternalEvent()");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    return global::Autodesk.Revit.UI.ExternalEvent.Create(this);");
            builder.Append(indent).AppendLine("}");
            SymbolUtilities.AppendPartialTypeEnd(builder, closeCount);
            source = builder.ToString();
            return true;
        }

        /// <summary>
        /// 生成 IUpdater 实现以及注册、触发器和注销代码。
        /// </summary>
        private static bool TryGenerateUpdater(
            SourceProductionContext context,
            INamedTypeSymbol symbol,
            out string source)
        {
            source = string.Empty;
            var methods = GetMarkedMethods(symbol, UpdaterHandlerAttribute).ToList();
            var validHandler = methods.Count == 1 && !methods[0].IsStatic && methods[0].ReturnsVoid &&
                               (methods[0].Parameters.Length == 0 ||
                                methods[0].Parameters.Length == 1 &&
                                methods[0].Parameters[0].Type.ToDisplayString() == "Autodesk.Revit.DB.UpdaterData");
            if (!validHandler)
            {
                ReportInvalidHandler(context, symbol, "UpdaterHandler");
                return false;
            }

            var attribute = SymbolUtilities.GetAttribute(symbol, RevitIncrementalGenerator.UpdaterAttribute);
            var name = attribute.ConstructorArguments.Length > 0
                ? attribute.ConstructorArguments[0].Value as string ?? symbol.Name
                : symbol.Name;
            var guidText = attribute.ConstructorArguments.Length > 1
                ? attribute.ConstructorArguments[1].Value as string ?? string.Empty
                : string.Empty;
            if (!Guid.TryParse(guidText, out _))
            {
                ReportConfiguration(context, symbol, $"Updater '{symbol.Name}' 的 GUID '{guidText}' 无效");
                return false;
            }

            var priority = SymbolUtilities.GetNamedArgument(attribute, "Priority", 100);
            var triggers = symbol.GetAttributes()
                .Where(item => item.AttributeClass?.ToDisplayString() == UpdaterTriggerAttribute)
                .ToList();
            if (triggers.Count == 0)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    GeneratorDiagnostics.NoUpdaterTrigger,
                    SymbolUtilities.GetLocation(symbol),
                    symbol.ToDisplayString()));
            }

            var builder = new StringBuilder("// <auto-generated/>\n");
            var closeCount = SymbolUtilities.AppendPartialTypeStart(
                builder, symbol, "global::Autodesk.Revit.DB.IUpdater");
            var indent = new string(' ', closeCount * 4);
            builder.Append(indent).AppendLine("private static global::Autodesk.Revit.DB.UpdaterId __updaterId;");
            builder.Append(indent).Append("private static ").Append(SymbolUtilities.GetCodeTypeName(symbol))
                .AppendLine(" __updaterInstance;");
            builder.Append(indent).AppendLine("public void Execute(global::Autodesk.Revit.DB.UpdaterData data)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).Append("    this.").Append(methods[0].Name).Append('(');
            if (methods[0].Parameters.Length == 1) builder.Append("data");
            builder.AppendLine(");");
            builder.Append(indent).AppendLine("}");
            builder.Append(indent).AppendLine("public global::Autodesk.Revit.DB.UpdaterId GetUpdaterId() => __updaterId;");
            builder.Append(indent).Append("public string GetUpdaterName() => \"")
                .Append(SymbolUtilities.EscapeString(name)).AppendLine("\";");
            builder.Append(indent).Append("public string GetAdditionalInformation() => \"Generated by RevitGen\";").AppendLine();
            builder.Append(indent).Append("public global::Autodesk.Revit.DB.ChangePriority GetChangePriority() => ")
                .Append("(global::Autodesk.Revit.DB.ChangePriority)").Append(priority).AppendLine(";");
            AppendUpdaterRegistration(builder, indent, symbol, guidText, triggers);
            SymbolUtilities.AppendPartialTypeEnd(builder, closeCount);
            source = builder.ToString();
            return true;
        }

        /// <summary>
        /// 写入 Updater 注册、触发器和注销方法。
        /// </summary>
        private static void AppendUpdaterRegistration(
            StringBuilder builder,
            string indent,
            INamedTypeSymbol symbol,
            string guidText,
            IReadOnlyList<AttributeData> triggers)
        {
            builder.Append(indent).AppendLine("internal static void __RevitGenRegister(global::Autodesk.Revit.UI.UIControlledApplication application)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).Append("    __updaterId = new global::Autodesk.Revit.DB.UpdaterId(application.ActiveAddInId, new global::System.Guid(\"")
                .Append(guidText).AppendLine("\"));");
            builder.Append(indent).Append("    __updaterInstance = new ").Append(SymbolUtilities.GetCodeTypeName(symbol)).AppendLine("();");
            builder.Append(indent).AppendLine("    if (!global::Autodesk.Revit.DB.UpdaterRegistry.IsUpdaterRegistered(__updaterId))");
            builder.Append(indent).AppendLine("        global::Autodesk.Revit.DB.UpdaterRegistry.RegisterUpdater(__updaterInstance);");

            foreach (var trigger in triggers)
            {
                var category = (int)(trigger.ConstructorArguments[0].Value ?? 0);
                var changeType = (int)(trigger.ConstructorArguments[1].Value ?? 0);
                var parameter = SymbolUtilities.GetNamedArgument(trigger, "BuiltInParameter", 0);
                builder.Append(indent).Append("    global::Autodesk.Revit.DB.UpdaterRegistry.AddTrigger(__updaterId, ")
                    .Append("new global::Autodesk.Revit.DB.ElementCategoryFilter((global::Autodesk.Revit.DB.BuiltInCategory)(")
                    .Append(category).Append(")), ").Append(GetChangeTypeExpression(changeType, parameter)).AppendLine(");");
            }

            builder.Append(indent).AppendLine("}");
            builder.Append(indent).AppendLine("internal static void __RevitGenUnregister()");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    if (__updaterId != null && global::Autodesk.Revit.DB.UpdaterRegistry.IsUpdaterRegistered(__updaterId))");
            builder.Append(indent).AppendLine("        global::Autodesk.Revit.DB.UpdaterRegistry.UnregisterUpdater(__updaterId);");
            builder.Append(indent).AppendLine("}");
        }

        /// <summary>
        /// 将特性中的变更类型转换为 Revit ChangeType 表达式。
        /// </summary>
        private static string GetChangeTypeExpression(int changeType, int parameter)
        {
            switch (changeType)
            {
                case 0: return "global::Autodesk.Revit.DB.Element.GetChangeTypeElementAddition()";
                case 1: return "global::Autodesk.Revit.DB.Element.GetChangeTypeElementDeletion()";
                case 2: return "global::Autodesk.Revit.DB.Element.GetChangeTypeGeometry()";
                case 3:
                    return "global::Autodesk.Revit.DB.Element.GetChangeTypeParameter(new global::Autodesk.Revit.DB.ElementId(" + parameter + "))";
                default: return "global::Autodesk.Revit.DB.Element.GetChangeTypeAny()";
            }
        }

        /// <summary>
        /// 生成 Revit 事件的对称订阅和取消订阅代码。
        /// </summary>
        private static bool TryGenerateEventContainer(
            SourceProductionContext context,
            INamedTypeSymbol symbol,
            out string source)
        {
            var eventMethods = symbol.GetMembers().OfType<IMethodSymbol>()
                .Where(method => SymbolUtilities.HasAttribute(method, RevitEventAttribute))
                .ToList();
            if (eventMethods.Count == 0)
            {
                ReportConfiguration(context, symbol, $"事件容器 '{symbol.Name}' 至少需要一个 [RevitEvent] 方法");
                source = string.Empty;
                return false;
            }
            foreach (var method in eventMethods)
            {
                var eventAttribute = SymbolUtilities.GetAttribute(method, RevitEventAttribute);
                var kind = (int)(eventAttribute.ConstructorArguments[0].Value ?? 0);
                var expectedArgs = GetEventArgsType(kind);
                var valid = !method.IsStatic && method.ReturnsVoid && method.Parameters.Length == 2 &&
                            method.Parameters[0].Type.SpecialType == SpecialType.System_Object &&
                            method.Parameters[1].Type.ToDisplayString() == expectedArgs;
                if (valid) continue;

                ReportInvalidHandler(context, symbol, "RevitEvent");
                source = string.Empty;
                return false;
            }

            var builder = new StringBuilder("// <auto-generated/>\n");
            var closeCount = SymbolUtilities.AppendPartialTypeStart(builder, symbol, string.Empty);
            var indent = new string(' ', closeCount * 4);
            builder.Append(indent).Append("private static ").Append(SymbolUtilities.GetCodeTypeName(symbol))
                .AppendLine(" __eventInstance;");
            builder.Append(indent).AppendLine("internal static void __RevitGenRegister(global::Autodesk.Revit.UI.UIControlledApplication application)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).Append("    __eventInstance = new ").Append(SymbolUtilities.GetCodeTypeName(symbol)).AppendLine("();");
            AppendEventAssignments(builder, indent + "    ", eventMethods, "+=");
            builder.Append(indent).AppendLine("}");
            builder.Append(indent).AppendLine("internal static void __RevitGenUnregister(global::Autodesk.Revit.UI.UIControlledApplication application)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    if (__eventInstance == null) return;");
            AppendEventAssignments(builder, indent + "    ", eventMethods, "-=");
            builder.Append(indent).AppendLine("    __eventInstance = null;");
            builder.Append(indent).AppendLine("}");
            SymbolUtilities.AppendPartialTypeEnd(builder, closeCount);
            source = builder.ToString();
            return true;
        }

        /// <summary>
        /// 写入事件订阅或取消订阅语句。
        /// </summary>
        private static void AppendEventAssignments(
            StringBuilder builder,
            string indent,
            IEnumerable<IMethodSymbol> methods,
            string operation)
        {
            foreach (var method in methods)
            {
                var attribute = SymbolUtilities.GetAttribute(method, RevitEventAttribute);
                var kind = (int)(attribute.ConstructorArguments[0].Value ?? 0);
                builder.Append(indent).Append(GetEventOwner(kind)).Append('.').Append(GetEventName(kind))
                    .Append(' ').Append(operation).Append(" __eventInstance.").Append(method.Name).AppendLine(";");
            }
        }

        /// <summary>
        /// 获取事件所属的 Revit Application 对象。
        /// </summary>
        private static string GetEventOwner(int kind)
        {
            return kind <= 2 ? "application" : "application.ControlledApplication";
        }

        /// <summary>
        /// 获取枚举对应的 Revit 事件名称。
        /// </summary>
        private static string GetEventName(int kind)
        {
            var names = new[]
            {
                "Idling", "ViewActivated", "DialogBoxShowing", "DocumentOpened", "DocumentClosing",
                "DocumentClosed", "DocumentChanged", "DocumentSaved", "DocumentSynchronizedWithCentral"
            };
            return kind >= 0 && kind < names.Length ? names[kind] : names[0];
        }

        /// <summary>
        /// 获取事件对应的 EventArgs 完整类型名。
        /// </summary>
        private static string GetEventArgsType(int kind)
        {
            var names = new[]
            {
                "Autodesk.Revit.UI.Events.IdlingEventArgs",
                "Autodesk.Revit.UI.Events.ViewActivatedEventArgs",
                "Autodesk.Revit.UI.Events.DialogBoxShowingEventArgs",
                "Autodesk.Revit.DB.Events.DocumentOpenedEventArgs",
                "Autodesk.Revit.DB.Events.DocumentClosingEventArgs",
                "Autodesk.Revit.DB.Events.DocumentClosedEventArgs",
                "Autodesk.Revit.DB.Events.DocumentChangedEventArgs",
                "Autodesk.Revit.DB.Events.DocumentSavedEventArgs",
                "Autodesk.Revit.DB.Events.DocumentSynchronizedWithCentralEventArgs"
            };
            return kind >= 0 && kind < names.Length ? names[kind] : names[0];
        }

        /// <summary>
        /// 生成 IDockablePaneProvider 实现和启动注册方法。
        /// </summary>
        private static bool TryGenerateDockablePane(
            SourceProductionContext context,
            INamedTypeSymbol symbol,
            out string source)
        {
            var attribute = SymbolUtilities.GetAttribute(symbol, RevitIncrementalGenerator.DockablePaneAttribute);
            var guidText = attribute.ConstructorArguments[0].Value as string ?? string.Empty;
            var title = attribute.ConstructorArguments[1].Value as string ?? symbol.Name;
            if (!Guid.TryParse(guidText, out _))
            {
                ReportConfiguration(context, symbol, $"DockablePane '{symbol.Name}' 的 GUID '{guidText}' 无效");
                source = string.Empty;
                return false;
            }
            if (symbol.IsAbstract || !InheritsFrom(symbol, "System.Windows.FrameworkElement") ||
                !symbol.InstanceConstructors.Any(constructor =>
                    constructor.Parameters.Length == 0 && constructor.DeclaredAccessibility != Accessibility.Private))
            {
                ReportConfiguration(
                    context,
                    symbol,
                    $"DockablePane '{symbol.Name}' 必须继承 FrameworkElement，并提供可访问的无参数构造函数");
                source = string.Empty;
                return false;
            }

            var position = SymbolUtilities.GetNamedArgument(attribute, "InitialPosition", 0);
            var minWidth = SymbolUtilities.GetNamedArgument(attribute, "MinimumWidth", 0);
            var minHeight = SymbolUtilities.GetNamedArgument(attribute, "MinimumHeight", 0);
            var builder = new StringBuilder("// <auto-generated/>\n");
            var closeCount = SymbolUtilities.AppendPartialTypeStart(
                builder, symbol, "global::Autodesk.Revit.UI.IDockablePaneProvider");
            var indent = new string(' ', closeCount * 4);
            builder.Append(indent).AppendLine("public void SetupDockablePane(global::Autodesk.Revit.UI.DockablePaneProviderData data)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    data.FrameworkElement = this;");
            builder.Append(indent).AppendLine("    data.InitialState = new global::Autodesk.Revit.UI.DockablePaneState();");
            builder.Append(indent).Append("    data.InitialState.DockPosition = (global::Autodesk.Revit.UI.DockPosition)")
                .Append(position).AppendLine(";");
            if (minWidth > 0) builder.Append(indent).Append("    data.InitialState.MinimumWidth = ").Append(minWidth).AppendLine(";");
            if (minHeight > 0) builder.Append(indent).Append("    data.InitialState.MinimumHeight = ").Append(minHeight).AppendLine(";");
            builder.Append(indent).AppendLine("}");
            builder.Append(indent).AppendLine("internal static void __RevitGenRegister(global::Autodesk.Revit.UI.UIControlledApplication application)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).Append("    application.RegisterDockablePane(new global::Autodesk.Revit.UI.DockablePaneId(new global::System.Guid(\"")
                .Append(guidText).Append("\")), \"").Append(SymbolUtilities.EscapeString(title)).Append("\", new ")
                .Append(SymbolUtilities.GetCodeTypeName(symbol)).AppendLine("());");
            builder.Append(indent).AppendLine("}");
            SymbolUtilities.AppendPartialTypeEnd(builder, closeCount);
            source = builder.ToString();
            return true;
        }

        /// <summary>
        /// 生成 Extensible Storage Schema 和模型读写方法。
        /// </summary>
        private static bool TryGenerateSchema(
            SourceProductionContext context,
            INamedTypeSymbol symbol,
            out string source)
        {
            var attribute = SymbolUtilities.GetAttribute(symbol, RevitIncrementalGenerator.SchemaAttribute);
            var guidText = attribute.ConstructorArguments[0].Value as string ?? string.Empty;
            var schemaName = attribute.ConstructorArguments[1].Value as string ?? symbol.Name;
            if (!Guid.TryParse(guidText, out _))
            {
                ReportConfiguration(context, symbol, $"Schema '{symbol.Name}' 的 GUID '{guidText}' 无效");
                source = string.Empty;
                return false;
            }

            var properties = symbol.GetMembers().OfType<IPropertySymbol>()
                .Where(property => SymbolUtilities.HasAttribute(property, SchemaFieldAttribute))
                .ToList();
            if (properties.Count == 0 || properties.Any(property => property.GetMethod == null || property.SetMethod == null))
            {
                ReportConfiguration(context, symbol, $"Schema '{symbol.Name}' 至少需要一个可读写的 [RevitSchemaField] 属性");
                source = string.Empty;
                return false;
            }
            if (properties.GroupBy(GetSchemaFieldName, StringComparer.Ordinal).Any(group => group.Count() > 1))
            {
                ReportConfiguration(context, symbol, $"Schema '{symbol.Name}' 包含重复字段名");
                source = string.Empty;
                return false;
            }
            var unsupportedProperty = properties.FirstOrDefault(property => !IsSupportedSchemaType(property.Type));
            if (unsupportedProperty != null)
            {
                ReportConfiguration(
                    context,
                    unsupportedProperty,
                    $"Schema 字段 '{unsupportedProperty.Name}' 的类型 '{unsupportedProperty.Type.ToDisplayString()}' 不受支持");
                source = string.Empty;
                return false;
            }

            var builder = new StringBuilder("// <auto-generated/>\n");
            var closeCount = SymbolUtilities.AppendPartialTypeStart(builder, symbol, string.Empty);
            var indent = new string(' ', closeCount * 4);
            builder.Append(indent).AppendLine("public static global::Autodesk.Revit.DB.ExtensibleStorage.Schema GetOrCreateSchema()");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).Append("    var schemaId = new global::System.Guid(\"").Append(guidText).AppendLine("\");");
            builder.Append(indent).AppendLine("    var existing = global::Autodesk.Revit.DB.ExtensibleStorage.Schema.Lookup(schemaId);");
            builder.Append(indent).AppendLine("    if (existing != null)");
            builder.Append(indent).AppendLine("    {");
            foreach (var property in properties)
            {
                var fieldName = GetSchemaFieldName(property);
                var valueType = property.Type is IArrayTypeSymbol arrayType
                    ? arrayType.ElementType
                    : property.Type;
                var valueTypeName = valueType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                builder.Append(indent).Append("        var existing_").Append(property.Name)
                    .Append(" = existing.GetField(\"").Append(SymbolUtilities.EscapeString(fieldName)).AppendLine("\");");
                builder.Append(indent).Append("        if (existing_").Append(property.Name)
                    .Append(" == null || existing_").Append(property.Name).Append(".ValueType != typeof(")
                    .Append(valueTypeName).AppendLine("))");
                builder.Append(indent).Append("            throw new global::System.InvalidOperationException(\"已存在的 Schema 字段 '")
                    .Append(SymbolUtilities.EscapeString(fieldName)).AppendLine("' 与生成模型不一致。\");");
            }
            builder.Append(indent).AppendLine("        return existing;");
            builder.Append(indent).AppendLine("    }");
            builder.Append(indent).AppendLine("    var schemaBuilder = new global::Autodesk.Revit.DB.ExtensibleStorage.SchemaBuilder(schemaId);");
            builder.Append(indent).Append("    schemaBuilder.SetSchemaName(\"").Append(SymbolUtilities.EscapeString(schemaName)).AppendLine("\");");
            AppendSchemaMetadata(builder, indent, attribute);
            foreach (var property in properties) AppendSchemaField(builder, indent, property);
            builder.Append(indent).AppendLine("    return schemaBuilder.Finish();");
            builder.Append(indent).AppendLine("}");
            AppendSchemaReadWrite(builder, indent, symbol, properties);
            SymbolUtilities.AppendPartialTypeEnd(builder, closeCount);
            source = builder.ToString();
            return true;
        }

        /// <summary>
        /// 写入 Schema 的可选说明和 VendorId。
        /// </summary>
        private static void AppendSchemaMetadata(StringBuilder builder, string indent, AttributeData attribute)
        {
            var documentation = SymbolUtilities.GetNamedArgument(attribute, "Documentation", string.Empty);
            var vendorId = SymbolUtilities.GetNamedArgument(attribute, "VendorId", string.Empty);
            if (!string.IsNullOrEmpty(documentation))
                builder.Append(indent).Append("    schemaBuilder.SetDocumentation(\"")
                    .Append(SymbolUtilities.EscapeString(documentation)).AppendLine("\");");
            if (!string.IsNullOrEmpty(vendorId))
                builder.Append(indent).Append("    schemaBuilder.SetVendorId(\"")
                    .Append(SymbolUtilities.EscapeString(vendorId)).AppendLine("\");");
        }

        /// <summary>
        /// 写入单个 Schema 字段定义。
        /// </summary>
        private static void AppendSchemaField(StringBuilder builder, string indent, IPropertySymbol property)
        {
            var attribute = SymbolUtilities.GetAttribute(property, SchemaFieldAttribute);
            var fieldName = SymbolUtilities.GetNamedArgument(attribute, "Name", string.Empty);
            if (string.IsNullOrWhiteSpace(fieldName)) fieldName = property.Name;
            var documentation = SymbolUtilities.GetNamedArgument(attribute, "Documentation", string.Empty);
            var isArray = property.Type is IArrayTypeSymbol;
            var fieldType = isArray ? ((IArrayTypeSymbol)property.Type).ElementType : property.Type;
            var typeName = fieldType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            builder.Append(indent).Append("    var field_").Append(property.Name)
                .Append(isArray ? " = schemaBuilder.AddArrayField(\"" : " = schemaBuilder.AddSimpleField(\"")
                .Append(SymbolUtilities.EscapeString(fieldName))
                .Append("\", typeof(").Append(typeName).AppendLine("));");
            if (!string.IsNullOrEmpty(documentation))
                builder.Append(indent).Append("    field_").Append(property.Name).Append(".SetDocumentation(\"")
                    .Append(SymbolUtilities.EscapeString(documentation)).AppendLine("\");");
        }

        /// <summary>
        /// 写入 Schema 模型与 Entity 之间的转换方法。
        /// </summary>
        private static void AppendSchemaReadWrite(
            StringBuilder builder,
            string indent,
            INamedTypeSymbol symbol,
            IEnumerable<IPropertySymbol> properties)
        {
            builder.Append(indent).AppendLine("public global::Autodesk.Revit.DB.ExtensibleStorage.Entity ToEntity()");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    var schema = GetOrCreateSchema();");
            builder.Append(indent).AppendLine("    var entity = new global::Autodesk.Revit.DB.ExtensibleStorage.Entity(schema);");
            foreach (var property in properties)
            {
                var fieldName = GetSchemaFieldName(property);
                if (property.Type is IArrayTypeSymbol arrayType)
                {
                    var elementTypeName = arrayType.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    builder.Append(indent).Append("    entity.Set<global::System.Collections.Generic.IList<")
                        .Append(elementTypeName).Append(">>(schema.GetField(\"")
                        .Append(SymbolUtilities.EscapeString(fieldName)).Append("\"), this.").Append(property.Name).AppendLine(");");
                }
                else
                {
                    var typeName = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    builder.Append(indent).Append("    entity.Set<").Append(typeName).Append(">(schema.GetField(\"")
                        .Append(SymbolUtilities.EscapeString(fieldName)).Append("\"), this.").Append(property.Name).AppendLine(");");
                }
            }
            builder.Append(indent).AppendLine("    return entity;");
            builder.Append(indent).AppendLine("}");
            builder.Append(indent).Append("public static ").Append(SymbolUtilities.GetCodeTypeName(symbol))
                .AppendLine(" FromEntity(global::Autodesk.Revit.DB.ExtensibleStorage.Entity entity)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    if (!entity.IsValid()) throw new global::System.ArgumentException(\"Entity 无效\", nameof(entity));");
            builder.Append(indent).AppendLine("    var schema = GetOrCreateSchema();");
            builder.Append(indent).Append("    var result = new ").Append(SymbolUtilities.GetCodeTypeName(symbol)).AppendLine("();");
            foreach (var property in properties)
            {
                var fieldName = GetSchemaFieldName(property);
                if (property.Type is IArrayTypeSymbol arrayType)
                {
                    var elementTypeName = arrayType.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    builder.Append(indent).Append("    result.").Append(property.Name)
                        .Append(" = new global::System.Collections.Generic.List<").Append(elementTypeName)
                        .Append(">(entity.Get<global::System.Collections.Generic.IList<").Append(elementTypeName)
                        .Append(">>(schema.GetField(\"").Append(SymbolUtilities.EscapeString(fieldName)).AppendLine("\"))).ToArray();");
                }
                else
                {
                    var typeName = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    builder.Append(indent).Append("    result.").Append(property.Name).Append(" = entity.Get<")
                        .Append(typeName).Append(">(schema.GetField(\"").Append(SymbolUtilities.EscapeString(fieldName)).AppendLine("\"));");
                }
            }
            builder.Append(indent).AppendLine("    return result;");
            builder.Append(indent).AppendLine("}");
        }

        /// <summary>
        /// 获取属性对应的 Schema 字段名。
        /// </summary>
        private static string GetSchemaFieldName(IPropertySymbol property)
        {
            var attribute = SymbolUtilities.GetAttribute(property, SchemaFieldAttribute);
            var fieldName = SymbolUtilities.GetNamedArgument(attribute, "Name", string.Empty);
            return string.IsNullOrWhiteSpace(fieldName) ? property.Name : fieldName;
        }

        /// <summary>
        /// 判断字段类型是否属于 Revit 2020 起稳定支持的简单类型或其数组。
        /// </summary>
        private static bool IsSupportedSchemaType(ITypeSymbol type)
        {
            if (type is IArrayTypeSymbol arrayType) return IsSupportedSchemaType(arrayType.ElementType);
            switch (type.SpecialType)
            {
                case SpecialType.System_Byte:
                case SpecialType.System_Int16:
                case SpecialType.System_Int32:
                case SpecialType.System_Boolean:
                case SpecialType.System_Single:
                case SpecialType.System_Double:
                case SpecialType.System_String:
                    return true;
            }

            var name = type.ToDisplayString();
            return name == "System.Guid" ||
                   name == "Autodesk.Revit.DB.ElementId" ||
                   name == "Autodesk.Revit.DB.XYZ";
        }

        /// <summary>
        /// 生成共享参数描述表和一次扫描 BindingMap 的批量绑定方法。
        /// </summary>
        private static bool TryGenerateSharedParameters(
            SourceProductionContext context,
            INamedTypeSymbol symbol,
            out string source)
        {
            var members = symbol.GetMembers()
                .Where(member => SymbolUtilities.HasAttribute(member, SharedParameterAttribute))
                .ToList();
            if (members.Count == 0)
            {
                source = string.Empty;
                return false;
            }

            var definitions = new List<SharedParameterData>();
            foreach (var member in members)
            {
                var attribute = SymbolUtilities.GetAttribute(member, SharedParameterAttribute);
                var guidText = attribute.ConstructorArguments[0].Value as string ?? string.Empty;
                var name = attribute.ConstructorArguments[1].Value as string ?? member.Name;
                if (!Guid.TryParse(guidText, out _))
                {
                    ReportConfiguration(context, member, $"共享参数 '{name}' 的 GUID '{guidText}' 无效");
                    source = string.Empty;
                    return false;
                }

                var categoriesArgument = attribute.NamedArguments.FirstOrDefault(item => item.Key == "Categories");
                definitions.Add(new SharedParameterData
                {
                    Guid = guidText,
                    Name = name,
                    ParameterGroup = SymbolUtilities.GetNamedArgument(attribute, "ParameterGroup", 0),
                    BindingKind = SymbolUtilities.GetNamedArgument(attribute, "BindingKind", 0),
                    Visible = SymbolUtilities.GetNamedArgument(attribute, "Visible", true),
                    Categories = categoriesArgument.Key == null ||
                                 categoriesArgument.Value.Kind != TypedConstantKind.Array ||
                                 categoriesArgument.Value.Values.IsDefault
                        ? Array.Empty<int>()
                        : categoriesArgument.Value.Values.Select(value => (int)(value.Value ?? 0)).ToArray()
                });
            }

            if (definitions.GroupBy(item => item.Guid, StringComparer.OrdinalIgnoreCase).Any(group => group.Count() > 1))
            {
                ReportConfiguration(context, symbol, $"类型 '{symbol.Name}' 包含重复的共享参数 GUID");
                source = string.Empty;
                return false;
            }

            var builder = new StringBuilder("// <auto-generated/>\n");
            var closeCount = SymbolUtilities.AppendPartialTypeStart(builder, symbol, string.Empty);
            var indent = new string(' ', closeCount * 4);
            AppendSharedParameterDefinitionType(builder, indent);
            AppendSharedParameterDefinitions(builder, indent, definitions);
            AppendEnsureBindings(builder, indent);
            SymbolUtilities.AppendPartialTypeEnd(builder, closeCount);
            source = builder.ToString();
            return true;
        }

        /// <summary>
        /// 写入共享参数的不可变描述类型。
        /// </summary>
        private static void AppendSharedParameterDefinitionType(StringBuilder builder, string indent)
        {
            builder.Append(indent).AppendLine("public sealed class RevitGenSharedParameterDefinition");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    public global::System.Guid Guid { get; internal set; }");
            builder.Append(indent).AppendLine("    public string Name { get; internal set; }");
            builder.Append(indent).AppendLine("    public int ParameterGroup { get; internal set; }");
            builder.Append(indent).AppendLine("    public bool IsTypeBinding { get; internal set; }");
            builder.Append(indent).AppendLine("    public bool Visible { get; internal set; }");
            builder.Append(indent).AppendLine("    public int[] Categories { get; internal set; }");
            builder.Append(indent).AppendLine("}");
        }

        /// <summary>
        /// 写入共享参数描述表。
        /// </summary>
        private static void AppendSharedParameterDefinitions(
            StringBuilder builder,
            string indent,
            IEnumerable<SharedParameterData> definitions)
        {
            builder.Append(indent).AppendLine("public static global::System.Collections.Generic.IReadOnlyList<RevitGenSharedParameterDefinition> GetSharedParameterDefinitions()");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    return new RevitGenSharedParameterDefinition[]");
            builder.Append(indent).AppendLine("    {");
            foreach (var item in definitions)
            {
                builder.Append(indent).Append("        new RevitGenSharedParameterDefinition { Guid = new global::System.Guid(\"")
                    .Append(item.Guid).Append("\"), Name = \"").Append(SymbolUtilities.EscapeString(item.Name))
                    .Append("\", ParameterGroup = ").Append(item.ParameterGroup)
                    .Append(", IsTypeBinding = ").Append(item.BindingKind == 1 ? "true" : "false")
                    .Append(", Visible = ").Append(item.Visible ? "true" : "false")
                    .Append(", Categories = new int[] { ").Append(string.Join(", ", item.Categories)).AppendLine(" } },");
            }
            builder.Append(indent).AppendLine("    };");
            builder.Append(indent).AppendLine("}");
        }

        /// <summary>
        /// 写入共享参数的批量绑定方法；BindingMap 只遍历一次。
        /// </summary>
        private static void AppendEnsureBindings(StringBuilder builder, string indent)
        {
            builder.Append(indent).AppendLine("public static global::System.Collections.Generic.IReadOnlyList<string> EnsureSharedParameterBindings(global::Autodesk.Revit.DB.Document document, global::Autodesk.Revit.ApplicationServices.Application application, global::Autodesk.Revit.DB.DefinitionFile definitionFile)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    if (document == null) throw new global::System.ArgumentNullException(nameof(document));");
            builder.Append(indent).AppendLine("    if (application == null) throw new global::System.ArgumentNullException(nameof(application));");
            builder.Append(indent).AppendLine("    var existing = new global::System.Collections.Generic.HashSet<global::System.Guid>();");
            builder.Append(indent).AppendLine("    var iterator = document.ParameterBindings.ForwardIterator();");
            builder.Append(indent).AppendLine("    iterator.Reset();");
            builder.Append(indent).AppendLine("    while (iterator.MoveNext())");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).AppendLine("        var external = iterator.Key as global::Autodesk.Revit.DB.ExternalDefinition;");
            builder.Append(indent).AppendLine("        if (external != null) existing.Add(external.GUID);");
            builder.Append(indent).AppendLine("    }");
            builder.Append(indent).AppendLine("    var missing = new global::System.Collections.Generic.List<string>();");
            builder.Append(indent).AppendLine("    foreach (var item in GetSharedParameterDefinitions())");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).AppendLine("        if (existing.Contains(item.Guid)) continue;");
            builder.Append(indent).AppendLine("        global::Autodesk.Revit.DB.ExternalDefinition external = null;");
            builder.Append(indent).AppendLine("        if (definitionFile != null)");
            builder.Append(indent).AppendLine("        {");
            builder.Append(indent).AppendLine("            foreach (global::Autodesk.Revit.DB.DefinitionGroup group in definitionFile.Groups)");
            builder.Append(indent).AppendLine("            {");
            builder.Append(indent).AppendLine("                foreach (global::Autodesk.Revit.DB.Definition definition in group.Definitions)");
            builder.Append(indent).AppendLine("                {");
            builder.Append(indent).AppendLine("                    var candidate = definition as global::Autodesk.Revit.DB.ExternalDefinition;");
            builder.Append(indent).AppendLine("                    if (candidate != null && candidate.GUID == item.Guid) { external = candidate; break; }");
            builder.Append(indent).AppendLine("                }");
            builder.Append(indent).AppendLine("                if (external != null) break;");
            builder.Append(indent).AppendLine("            }");
            builder.Append(indent).AppendLine("        }");
            builder.Append(indent).AppendLine("        if (external == null) { missing.Add(item.Name); continue; }");
            builder.Append(indent).AppendLine("        var categories = application.Create.NewCategorySet();");
            builder.Append(indent).AppendLine("        foreach (var categoryId in item.Categories)");
            builder.Append(indent).AppendLine("        {");
            builder.Append(indent).AppendLine("            var category = global::Autodesk.Revit.DB.Category.GetCategory(document, (global::Autodesk.Revit.DB.BuiltInCategory)categoryId);");
            builder.Append(indent).AppendLine("            if (category != null) categories.Insert(category);");
            builder.Append(indent).AppendLine("        }");
            builder.Append(indent).AppendLine("        global::Autodesk.Revit.DB.Binding binding = item.IsTypeBinding");
            builder.Append(indent).AppendLine("            ? (global::Autodesk.Revit.DB.Binding)application.Create.NewTypeBinding(categories)");
            builder.Append(indent).AppendLine("            : application.Create.NewInstanceBinding(categories);");
            builder.Append(indent).AppendLine("        document.ParameterBindings.Insert(external, binding, (global::Autodesk.Revit.DB.BuiltInParameterGroup)item.ParameterGroup);");
            builder.Append(indent).AppendLine("    }");
            builder.Append(indent).AppendLine("    return missing;");
            builder.Append(indent).AppendLine("}");
        }

        private sealed class SharedParameterData
        {
            public string Guid { get; set; }
            public string Name { get; set; }
            public int ParameterGroup { get; set; }
            public int BindingKind { get; set; }
            public bool Visible { get; set; }
            public int[] Categories { get; set; }
        }

        /// <summary>
        /// 获取带指定方法特性的所有方法。
        /// </summary>
        private static IEnumerable<IMethodSymbol> GetMarkedMethods(INamedTypeSymbol symbol, string attributeName)
        {
            return symbol.GetMembers().OfType<IMethodSymbol>()
                .Where(method => SymbolUtilities.HasAttribute(method, attributeName));
        }

        /// <summary>
        /// 判断类型是否继承指定完整名称的基类。
        /// </summary>
        private static bool InheritsFrom(INamedTypeSymbol symbol, string baseTypeName)
        {
            for (var current = symbol.BaseType; current != null; current = current.BaseType)
            {
                if (current.ToDisplayString() == baseTypeName) return true;
            }
            return false;
        }

        /// <summary>
        /// 报告统一的 Handler 签名诊断。
        /// </summary>
        private static void ReportInvalidHandler(
            SourceProductionContext context,
            INamedTypeSymbol symbol,
            string handlerName)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                GeneratorDiagnostics.InvalidHandler,
                SymbolUtilities.GetLocation(symbol),
                symbol.ToDisplayString(),
                handlerName));
        }

        /// <summary>
        /// 报告统一的配置错误诊断。
        /// </summary>
        private static void ReportConfiguration(
            SourceProductionContext context,
            ISymbol symbol,
            string message)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                GeneratorDiagnostics.InvalidConfiguration,
                SymbolUtilities.GetLocation(symbol),
                message));
        }
    }
}
